# .github/workflows/ci.yml
name: ci

on: [push, pull_request]

jobs:
  ci:
    uses: catalyst/catalyst-moodle-workflows/.github/workflows/ci.yml@main
    with:
      min_php: 7.4
      extra_plugin_runners: |
        sudo apt-get update;
        sudo apt-get install -y ghostscript;
